### PR TITLE
Task together merge. Repeated reload fixed. Scroll together sync

### PR DESCRIPTION
**Pull request by ananddeb23**
Bug of repeated refreshes fixed. In addition, users in together session can now scroll in sync

### CODE REVIEW

**Comment by theSuiGenerisAakash** [comment]
Why 135 file changes? And 35000 insertions? Can we please check the PR to see what's wrong?

**Comment by ananddeb23** [comment]
135 file changes as I guess it carries many new files from togetherjs( the actual source of together) and 37 commits ( from me, Mahesh and one from Sahil)

**Comment by maheshhp** [comment]
I think many files got added as we compiled a local copy of the TogetherJS library and added it. If possible, please comment the actual files change in our source code files so that only they can be reviewed.

**Comment by ananddeb23** [comment]
MainMenu.js
index.html
package.json (socket.io client installed)

**Comment by maheshhp** [comment]
I have worked on the following components mainly:
Footer
ProductDisplay
ProductContainer

Styles of product display page, product category page and the header and footer.

**Comment by maheshhp** [comment]
Is it fine to remove the TogetherJS files since we have reverted to using the online library?

**Comment by ananddeb23** [comment]
@maheshhp  I think we can. It would also reduce the number of files which we are anyway not currently using.

**Comment by ananddeb23** [comment]
I think now it can be easily reviewed. Good job Mahesh!

**Comment by aditiverma1009** [comment]
A few issues that I noticed-
Due to network lag, scrolling too fast might be a problem.
In case there are no products in category page (when filter is applied), the footer does not stick to the bottom of the page and moves into the main container.
Page change doesn't respond sometimes due to network lag.
When we type in filter search field, the input target value should not reflect on co-shoppers input field at all. (Need fixing)

**Pull request merged**
